name: Release
on:
  push:
    branches:
      - master
jobs:
  CurrentTag:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_TAG: ${{ steps.save-current-tag.outputs.CURRENT_TAG }}
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get current tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save current tag
        id: save-current-tag
        run: echo '::set-output name=CURRENT_TAG::${{ steps.current-tag.outputs.tag }}'
  Release:
    runs-on: ubuntu-latest
    needs: [CurrentTag]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Website test with coverage
        run: npm run test:website:ci:coverage
      - name: Website build
        run: npm run build:website:gh-pages
        env:
          CI: true
      - name: Website Storybook
        run: npm run storybook:build-with-docs:website:gh-pages
      - name: Website Compodoc
        run: npm run compodoc:website:gh-pages
      - name: Release
        run: npm run semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy to GitHub pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions <geoffrey.testelin@gmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR:
    runs-on: ubuntu-latest
    needs: [CurrentTag, Release]
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Reset branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show current tag
        run: echo 'The current tag is ${{ needs.CurrentTag.outputs.CURRENT_TAG }}'
      - name: Has same tag
        if: needs.CurrentTag.outputs.CURRENT_TAG == steps.latest-tag.outputs.tag
        run: echo 'The current tag did not change'
      - name: Has new tag
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        run: echo 'The current tag is not the same after the release. A new tag has been created'
      - name: Create PR from master to develop
        if: needs.CurrentTag.outputs.CURRENT_TAG != steps.latest-tag.outputs.tag
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'chore(develop): merge master into develop due to new version ${{ steps.latest-tag.outputs.tag }}'
          branch: feature/merge-master-into-develop
          assignees: C0ZEN
          commit-message: 'chore(develop): merge master into develop'
          body: |
            :tada: This PR was generated after the creation of the version ${{ steps.latest-tag.outputs.tag }} :tada:

            The release is available on:
            - [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sonia-corporation/ngx-achievements/v/${{ steps.latest-tag.outputs.tag }})
            - [GitHub release](https://github.com/Sonia-corporation/ngx-achievements/releases/tag/${{ steps.latest-tag.outputs.tag }})

            Your **github-actions** bot :rocket:
